version: "3.9"

services:

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - plugins.ml_commons.only_run_on_ml_node=false
      - plugins.ml_commons.native_memory_threshold=100
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
    volumes:
      - opensearch-volume:/usr/share/opensearch/data
    restart: unless-stopped
    dns:
      - 8.8.8.8
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    restart: unless-stopped
    dns:
      - 8.8.8.8
    networks:
      - opensearch-net

volumes:
  opensearch-volume:

networks:
  opensearch-net:
    driver: bridge
